version: '3.8'
services:
  app:
    #container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    #networks:
     # - nginx_net
    ports:
      - '80:80' 
      - '443:443'
      - '81:81' # Puerto de administración
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DISABLE_IPV6: 'true'
      DB_MYSQL_USER: ${MARIADB_DATABASE_USER}
      DB_MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      DB_MYSQL_NAME: ${MARIADB_DATABASE_NAME}
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ${NGINX_HOME}/data:/data
      - ${NGINX_HOME}/letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    #container_name: mariadb
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    #networks:
     # - nginx_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE_NAME}
      MYSQL_USER: ${MARIADB_DATABASE_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ${NGINX_HOME}/mysql:/var/lib/mysql

#networks:
 #nginx_net:
  # driver: bridge
   #ipam:
    # config:
     #  - subnet: 10.5.0.0/16
      #   gateway: 10.5.0.1
       #  aux_addresses:
        #  nginx: 10.5.0.6
         # mariadb: 10.5.0.5
